baseURL = '/'
languageCode = 'en-us'
title = 'Nina Jensen'
enableEmoji = true

[params]
  custom_css = ["css/iosevka.css", "css/iosevka-aile.css", "css/iosevka-etoile.css"]

  [params.navbar]
  use = false
  
  [params.extensions]
  use = true
  ext = ".txt" # extension to add after single page
    
  # Note: This is for the meta description, which is different from the "description" displayed in the terminal.
  description = ""
  [params.terminal]
  scheme = "OceanDark"

  userName = "nina"
  pcName = "jensen"
  workDir = ""
  profile = "hello.md"

  ps1Delay = 0 # prompt speed : [userName]@[pcName]:~/$ , [userName]@[pcName]:~/[workDir]$
  stdoutDelay = 0 # stdout speed : [description] , files in Params.Tree
  commandDelay = 50 # command speed : cd [workDir] , cat [profile] , tree ./[folderName]/


  titleDelay = 0 
  contentDelay = 0 
  description = "/hello.md"

  [params.tree]
  use = true
  folderName = "index"
  files = [ 
    ["curriculum-vitae", "/cv.md"],
    ["contributions", "/contributions.md"],
    ["interests", "/interests.md"],
  ]
